export const FETCH_API_NUMBER_TABLE = "FETCH_API_NUMBER_TABLE";
export const FETCH_API_NUMBER_TABLE_SUCCESS = "FETCH_API_NUMBER_TABLE_SUCCESS";
export const FETCH_API_NUMBER_TABLE_ERR = "FETCH_API_NUMBER_TABLE_ERR";
