export const FETCH_API_NUMBER_TABLE = "FETCH_API_NUMBER_TABLE";
export const FETCH_API_NUMBER_TABLE_SUCCESS = "FETCH_API_NUMBER_TABLE_SUCCESS";
export const FETCH_API_NUMBER_TABLE_ERR = "FETCH_API_NUMBER_TABLE_ERR";

export const POST_API_NUMBER_TABLE = "POST_API_NUMBER_TABLE";
export const POST_API_NUMBER_TABLE_SUCCESS = "POST_API_NUMBER_TABLE_SUCCESS";
export const POST_API_NUMBER_TABLE_ERR = "POST_API_NUMBER_TABLE_ERR";

export const DELETE_API_NUMBER_TABLE = "DELETE_API_NUMBER_TABLE";
export const DELETE_API_NUMBER_TABLE_SUCCESS =
  "DELETE_API_NUMBER_TABLE_SUCCESS";
export const DELETE_API_NUMBER_TABLE_ERR = "DELETE_API_NUMBER_TABLE_ERR";
