export const FETCH_API_TABLE_CODE = "FETCH_API_TABLE_CODE";
export const FETCH_API_TABLE_CODE_SUCCESS = "FETCH_API_TABLE_CODE_SUCCESS";
export const FETCH_API_TABLE_CODE_ERR = "FETCH_API_TABLE_CODE_ERR";
